### ISSUE TITLE
[Related] tikzjax

### ISSUE THREAD

**Issue by WilliamCappelletti** [thequilo/obsidian-tikz-renderer#3]
The [tikzjax](https://github.com/kisonecat/tikzjax) javascript module does something very similar, maybe a future version could wrap it up. Thanks for the work! 😄

**Comment by thequilo** [comment]
Yes, I saw that project. It translated the tikz code into webassembly to build tikz in the browser. It would be great to get this functionality integrated because it would run on any platform. The current state of the tikzjax project is unfortunately very inflexible (https://github.com/kisonecat/tikzjax/issues/8). It only compiles tikz on page load. We would need to call it from the extension code whenever a tikz code block changes. Once that is possible, I would be happy to add it as a backend! 

I'm not sure about this, but it could actually run faster than a local latex installation because tikzjax runs fully in the browser which eliminates slow file system communication. 

I'll keep this issue open as a reminder

**Comment by thequilo** [comment]
I just found the obsidian tikzjax plugin (https://github.com/artisticat1/obsidian-tikzjax) which implements this. It uses a fork of the tikzjax library.

I guess now this plugin is obsolete because tikzjax is much more portable than my script solution.

**Comment by WilliamCappelletti** [comment]
Oh, that seems quite powerful indeed. Thanks for your work anyway, it has been useful!
