### ISSUE TITLE
"registerMarkdownCodeBlockProcessor" instead of "registerMarkdownPostProcessor"

### ISSUE THREAD

**Issue by hsianktin** [thequilo/obsidian-tikz-renderer#5]
Thanks for your novel plugin. I'm not a front-end programmer, either. I just have an immature suggestion.

Current version of Obsidian supports live preview of code blocks with a registered Markdown code block processer. I'm a big fan of the live preview editor mode. So, I think it could be a good idea implement the tikz renderer in this mode. 

The following code should render code block starting with `tikzpicture` correctly in the live preview mode.

```javascript
      this.registerMarkdownCodeBlockProcessor('tikzpicture', (source,el, ctx) => {
        el.innerHTML = '<div class="tikz-preview-rendering">rendering tikz...</div>';
        el.addClass("tikz-preview", "tikz-preview-image-only");
        this.renderTikz2SVG(source).then((data) => {
          // console.log(data);
          el.innerHTML = data;
        }).catch((err) => {
          // console.log(err);
          el.innerText = err;
        });
```

However, the drawback is that it could be a little bit difficult to implement the side-by-side mode.

**Comment by thequilo** [comment]
Hi @hsianktin! Your suggestion sounds reasonable. Actually, my first implementation used the `registerMarkdownCodeBlockProcessor` function. The problem I had with that is that it breaks syntax highlighting because Obsidian (or probably HyperMD) doesn't know `tikpicture` as a language and I didn't find a way to add a new language. 

Also I wanted to have the `side-by-side` mode. Using the `MarkdownCodeBlockProcessor` doesn't allow parsing the "header" line of the code block. You can only bind a postprocessor to the first word of the line. While the current implementation allows for a rudimentary implementation of this, it doesn't update the rendered output when only the header arguments are modified (see https://github.com/thequilo/obsidian-tikz-renderer/issues/4#issuecomment-1103646318). This could be solved removing the arguments from the header line and introducing special comments, e.g., `%obsidian-tikz-side-by-side`.

If there is a way to teach Obsidian a a new language for syntax highlighting (or simply re-use the latex highlighting for `tikzpicture`), I am happy to switch as it also makes the rendering code simpler.

**Comment by hsianktin** [comment]
Thanks for sharing your opinions. For syntax highlighting, I'm trying to come up with an alternative way. Obsidian uses Prism as their syntax highlight backend. On Prismjs website,  LaTeX has aliases latex,  tex,  and context. I'm wondering if it is plausible to bind the processor to the "context" code block as a workaround.-------- Original message --------From: Thilo von Neumann ***@***.***>Date: Thu, Apr 21, 2022, 11:43 PMTo: thequilo/obsidian-tikz-renderer ***@***.***>Cc: hsianktin ***@***.***>, Mention ***@***.***>Subject: Re: [thequilo/obsidian-tikz-renderer] "registerMarkdownCodeBlockProcessor" instead of "registerMarkdownPostProcessor" (Issue #5)
Hi @hsianktin! Your suggestion sounds reasonable. Actually, my first implementation used the registerMarkdownCodeBlockProcessor function. The problem I had with that is that it breaks syntax highlighting because Obsidian (or probably HyperMD) doesn't know tikpicture as a language and I didn't find a way to add a new language.
Also I wanted to have the side-by-side mode. Using the MarkdownCodeBlockProcessor doesn't allow parsing the "header" line of the code block. You can only bind a postprocessor to the first word of the line. While the current implementation allows for a rudimentary implementation of this, it doesn't update the rendered output when only the header arguments are modified (see #4 (comment)). This could be solved removing the arguments from the header line and introducing special comments, e.g., %obsidian-tikz-side-by-side.
If there is a way to teach Obsidian a a new language for syntax highlighting (or simply re-use the latex highlighting for tikzpicture), I am happy to switch as it also makes the rendering code simpler.

**Comment by thequilo** [comment]
For preview mode, doing `Prism.languages.tikzpicture = Prism.languages.latex` works, but it doesn't work in edit mode for me.

**Comment by hsianktin** [comment]
Oh, I meant some more "stupid" solution. In the plugin, instead of telling obsidian it's handling "tikzpicture" language, just handle "tex" code. Anything in the "tex" code block will be compiled and converted into SVG. It will absolutely support syntax highlight then. But it may still lack support for side-by-side mode. That's a big issue.-------- Original message --------From: Thilo von Neumann ***@***.***>Date: Fri, Apr 22, 2022, 2:10 AMTo: thequilo/obsidian-tikz-renderer ***@***.***>Cc: hsianktin ***@***.***>, Mention ***@***.***>Subject: Re: [thequilo/obsidian-tikz-renderer] "registerMarkdownCodeBlockProcessor" instead of "registerMarkdownPostProcessor" (Issue #5)
For preview mode, doing Prism.languages.tikzpicture = Prism.languages.latex works, but it doesn't work in edit mode for me.

**Comment by thequilo** [comment]
I won't do that because I don't want all tex code blocks to be rendered. It would be really annoying if any tex code block you have in your notes suddenly is rendered, and potentially doesn't include tikz code so the render even breaks

**Comment by hsianktin** [comment]
That's reasonable. Thanks for your explanation.
